demo/apps/accounts/urls.py
# encoding: utf-8


from django.conf.urls import patterns, url, include

urlpatterns = patterns('demo.apps.accounts.views',
    url(r'^check-mobile-phone/$', 'check_mobile_phone', name='check_mobile_phone'),
    url(r'^check-register-mobile-phone/$', 'check_register_mobile_phone', name='check_register_mobile_phone'),
    url(r'^check-username/$', 'check_username', name='check_username'),
    url(r'^check-introducer/$', 'check_introducer', name='check_introducer'),
    url(r'^register/$', 'register', name='register'),
    url(r'^send-captcha/$', 'send_captcha', name='send_captcha'),
    url(r'^user-agreement/$', 'user_agreement', name='user_agreement'),
    url(r'^set-identity/(?P<userprofile_id>\d+)/$', 'set_identity', name='set_identity'),
    url(r'^register-finish/(?P<user_id>\d+)/$', 'register_finish', name='register_finish'),
    url(r'^login/$', 'user_login', name='login'),
    url(r'^logout/$', 'user_logout', name='logout'),
    # url(r'^reset-password/$', 'reset_password', name='reset_password'),
    # url(r'^logout/$', 'user_logout', name='logout'),
    url(r'^forgetpw/$','forgetpw',name='forgetpw'),
    url(r'^resetpw/$','resetpw',name='resetpw'),
    url(r'^resetpw-finish/$','resetpw_finish',name = 'resetpw_finish'),
)

demo/apps/api/urls.py
# coding=utf-8
from django.conf.urls import patterns, url, include
from rest_framework.authentication import BasicAuthentication
from rest_framework_jwt.authentication import JSONWebTokenAuthentication

from demo.apps.api.views import (APIRegisterView, APIGetsmscodeView,
    APITestTokenView, APILoginView, APIGetimgverifycodeView, APIFindpwdView,
    APIResetpwdView, APICheckusernameView, APIUpdateusernameView, 
    APIGetOrdersView, APIGetOrderDetailView, APICancelOrderView)

urlpatterns = patterns('',
    url(r'^auth/', 'rest_framework_jwt.views.obtain_jwt_token', name='api_auth'),
)

urlpatterns += patterns('demo.apps.api.views',
    url(r'^test/$', APITestTokenView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='test'),
    # about account
    url(r'^getsmscode/$', APIGetsmscodeView.as_view(authentication_classes=[BasicAuthentication]), name='api_getsmscode'),
    url(r'^getimgverifycode/$', APIGetimgverifycodeView.as_view(authentication_classes=[BasicAuthentication]), name='api_getimgverifycode'),
    url(r'^findpwd/$', APIFindpwdView.as_view(authentication_classes=[BasicAuthentication]), name='api_findpwd'),
    url(r'^resetpwd/$', APIResetpwdView.as_view(authentication_classes=[BasicAuthentication]), name='api_resetpwd'),
    url(r'^checkusername/$', APICheckusernameView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='api_checkusername'),
    url(r'^updateusername/$', APIUpdateusernameView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='api_updateusername'),
    url(r'^register/$', APIRegisterView.as_view(authentication_classes=[BasicAuthentication]), name='api_register'),
    url(r'^login/$', APILoginView.as_view(authentication_classes=[BasicAuthentication]), name='api_login'),

    url(r'^getorderdetail/(?P<order_id>\d+)/$', APIGetOrderDetailView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='api_getorderdetail'),
    url(r'^cancelorder/(?P<order_id>\d+)/$', APICancelOrderView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='api_cancelorder'),
    url(r'^getorders/$', APIGetOrdersView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='api_getorders'),
)

demo/apps/helper/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required



urlpatterns = patterns('demo.apps.helper.views',
    url(r'^$', 'helper_index', name='helper_index'),
)

demo/urls.py
# -*- coding: utf-8 -*-s

"""demo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url, patterns
from django.conf import settings
from django.contrib import admin
from oscar.app import application

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('demo.apps.accounts.urls', namespace='accounts')),
    url(r'^helper/', include('demo.apps.helper.urls', namespace='helper')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'platform/', include('demo.apps.platform.urls', namespace='platform')),
    url(r'^api/', include('demo.apps.api.urls', namespace='api')),
    url(r'', include(application.urls)),
]

# 部署时下面两个注释要解开
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 部署时下面4行要注释 （这个是本地测试404页面用的）
urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT },name='media'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.STATICFILES_DIRS[0] },name='static'),
)

demo/apps/basket/models.py
from oscar.apps.basket.models import *  # noqa

demo/apps/checkout/models.py
from oscar.apps.checkout.models import *  # noqa

demo/apps/customer/models.py
from oscar.apps.customer.models import *  # noqa

demo/apps/accounts/forms.py
#!/usr/bin/env python
# encoding: utf-8


import re

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

from oscar.forms.widgets import ImageInput

from demo.apps.accounts.models import UserProfile,Captcha


def local_mobile_phone_validator(mobile_phone_number):
    phoneprefix=['130','131','132','133','134','135','136','137','138','139',
                 '150','151','152','153','156','158','159','170', '171', '172',
                 '178','181', '182','183','185','186','187','188','189']
    validator_str = r'^\d{11}$'
    validator_engine = re.compile(validator_str)

    if mobile_phone_number:
        if validator_engine.match(mobile_phone_number) and mobile_phone_number[0:3] in phoneprefix:
            return True
        else:
            return False
    else:
        return False


def local_identification_card_number_validator(identification_card_number):
    validator_str = '^(\d{6})(\d{4})(\d{2})(\d{2})(\d{3})([0-9]|X)$'
    validator_engine = re.compile(validator_str)

    if identification_card_number:
        if validator_engine.match(identification_card_number):
            return True
        else:
            return False
    else:
        return True


def local_phone_validator(phone_number):
    validator_str = r'(^(\d{11})$|^((\d{7,8})|(\d{4}|\d{3})-(\d{7,8}))$)'
    validator_engine = re.compile(validator_str)

    if phone_number:
        if validator_engine.match(phone_number):
            return True
        else:
            return False
    else:
        return True


class RegisterForm(forms.Form):
    username = forms.CharField(label=u'用户名', max_length=64, required=True,
            widget = forms.TextInput(attrs = {"onfocus": "OnfocusFun(this,'请输入用户名,6-20位字母数字')",
                                        "onblur": "OnBlurFun(this, '请输入用户名,6-20位字母数字')"}))
    password = forms.CharField(label=u'密码', max_length=64, required=True,
                               widget=forms.PasswordInput)
    re_password = forms.CharField(label=u'确认密码', max_length=64, required=True,
                                  widget=forms.PasswordInput)
    mobile_phone = forms.CharField(label=u'手机号', max_length=11, required=True,
                                   widget=forms.TextInput(attrs={'class': 'input-short'}))
    captcha = forms.CharField(label=u'验证码', max_length=32, required=True,
                              widget=forms.TextInput(attrs={'class': 'input-short'}))
    email = forms.EmailField(label=u'邮箱', required=False)
    introducer = forms.CharField(label=u'推荐人', max_length=64, required=False)
    user_agreement = forms.ChoiceField(label=u'用户协议', required=True,
                                       choices=((True, True), (False, False)),
                                       widget=forms.CheckboxInput(attrs={'checked':True}))

    def clean_username(self):
        data = self.cleaned_data['username']
        if data:
            try:
                user = User.objects.get(username=data)
                raise forms.ValidationError(u'用户名被占用。')
            except User.DoesNotExist:
                return data
        else:
            raise forms.ValidationError(u'用户名不可为空。')

    def clean_introducer(self):
        data = self.cleaned_data['introducer']
        if data:
            try:
                user = User.objects.get(username=data)
                return data
            except User.DoesNotExist:
                raise forms.ValidationError(u'没有这个用户，请重新输入。')
        return data

    def clean_re_password(self):
        cleaned_data = self.cleaned_data
        if 'password' in cleaned_data and 're_password' in cleaned_data:
            data = cleaned_data['re_password']
            password = cleaned_data['password']
            if password != data:
                raise forms.ValidationError(u'两次输入的密码不一致。')
        return cleaned_data

    def clean_mobile_phone(self):
        data = self.cleaned_data['mobile_phone']
        if not local_mobile_phone_validator(data):
            raise forms.ValidationError(u'手机号码不合法。')
        try:
            userprofile = UserProfile.objects.get(mobile_phone=data)
            raise forms.ValidationError(u'此号码已经被注册。')
        except UserProfile.DoesNotExist:
            pass
        return data

    def clean_captcha(self):
        cleaned_data = self.cleaned_data
        if 'mobile_phone' in cleaned_data:
            data = cleaned_data['captcha']
            mobile_phone = cleaned_data['mobile_phone']
            try:
                current_mobile_captcha = Captcha.objects.get(recipient=mobile_phone)
                if current_mobile_captcha.captcha != data:
                    raise forms.ValidationError(u'验证码不正确。')
            except Captcha.DoesNotExist:
                raise forms.ValidationError(u'验证码不正确。')
        else:
            if not self.data['mobile_phone']:
                raise forms.ValidationError(u'必须填手机号。')
        return cleaned_data

    def clean_email(self):
        data = self.cleaned_data['email']
        if data:
            try:
                user = User.objects.get(email=data)
                raise forms.ValidationError(u'此邮箱被占用。')
            except User.DoesNotExist:
                return data
        return data

    def clean_user_agreement(self):
        data = self.cleaned_data['user_agreement']
        if data == 'False':
            raise forms.ValidationError(u'必须同意用户协议。')
        return data


class IdentityForm(forms.ModelForm):
    '''
    real_name = forms.CharField(label=u'姓名', max_length=64, required=True)
    identification_card_number = forms.CharField(label=u'姓名', max_length=32, required=True)
    identification_card_image_front = forms.ImageField(upload_to='identification_card',
                                                        blank=True, null=True, verbose_name=u'身份证正面图')
    identification_card_image_back = forms.ImageField(upload_to='identification_card',
                                                       blank=True, null=True, verbose_name=u'身份证背面图')
    '''
    def __init__(self, *args, **kwargs):
        super(IdentityForm, self).__init__(*args, **kwargs)
        self.fields["real_name"].required = True
        self.fields["identification_card_number"].required = True
        self.fields["identification_card_image_front"].required = True
        self.fields["identification_card_image_back"].required = True

    class Meta:
        model = UserProfile
        fields = ['real_name', 'identification_card_number',
                  'identification_card_image_front', 'identification_card_image_back']
        '''
        widgets = {
            'identification_card_image_front': ImageInput(),
            'identification_card_image_back': ImageInput(),
        }
        '''

    def clean_identification_card_number(self):
        data = self.cleaned_data['identification_card_number']
        if not local_identification_card_number_validator(data):
            raise forms.ValidationError(u'身份证号码不合法。')
        return data


class LoginForm(AuthenticationForm):
    username = forms.CharField(label=u'用户名', max_length=64, required=True,
                               widget=forms.TextInput(attrs={'class': 'login-f-txtstyle',
                                                             "onfocus": "OnfocusFun(this, '请输入用户名')",
                                                             "onblur": "OnBlurFun(this, '请输入用户名')"}))
    password = forms.CharField(label=u'密码', max_length=64, required=True,
                               widget=forms.PasswordInput(attrs={'class': 'login-f-txtstyle',
                                                                 "onfocus": "OnfocusFun1(this, '请输入密码')",
                                                                 "onblur": "OnBlurFun1(this, '请输入密码')"}))

class ForgetPwForm(forms.Form):
    mobile_phone = forms.CharField(label=u'手机号', max_length=11, required=True,
                                   widget=forms.TextInput(attrs={'class': 'input-short'}))

    captcha = forms.CharField(label=u'验证码', max_length=32, required=True,
                              widget=forms.TextInput(attrs={'class': 'input-short'}))

    def clean_mobile_phone(self):
        data = self.cleaned_data['mobile_phone']

        if not local_mobile_phone_validator(data):
            raise forms.ValidationError(u'手机号码不合法。')
        try:
            userprofile = UserProfile.objects.get(mobile_phone=data)
        except:
            raise forms.ValidationError(u'此号码不为注册手机号。')
        return data


    def clean_captcha(self):
        cleaned_data = self.cleaned_data

        if 'mobile_phone' in cleaned_data:
            data = cleaned_data['captcha']
            mobile_phone = cleaned_data['mobile_phone']
            try:
                current_mobile_captcha = Captcha.objects.get(recipient=mobile_phone)
                if current_mobile_captcha.captcha != data:
                    print '*****'
                    print current_mobile_captcha.captcha
                    print '*****'
                    raise forms.ValidationError(u'验证码不正确。')
            except Captcha.DoesNotExist:
                raise forms.ValidationError(u'验证码不正确。')
        else:
            raise forms.ValidationError(u'验证码不正确。')

        return cleaned_data['captcha']

class ResetPwForm(forms.Form):
    password = forms.CharField(label=u'新密码', max_length=64, required=True,
                               widget=forms.PasswordInput(attrs = {"onfocus": "OnfocusFun1(this, '请输入密码')",
                                                                   "onblur" : "OnBlurFun1(this, '请输入密码')" ,
                                                                   "onkeyup":"pwStrength(this.value)" ,
                                                                   }))
    re_password = forms.CharField(label=u'确认密码', max_length=64, required=True,

demo/apps/customer/assets/forms.py
# -*- coding: utf-8 -*-

from django import forms
from demo.apps.commission.models import UserBank

from demo.apps.customer.assets.utils import is_valid_mobile, is_valid_bank_card_num, is_valid_bank


class BankCardForm(forms.ModelForm):

    def __init__(self, user,*args, **kwargs):
        self.user = user
        super(self.__class__, self).__init__(*args, **kwargs)
        # self.fields["user_name"].required = True
        # self.fields["id_card"].required = True
        # self.user = user
        self.fields["bank_name"].required = True
        self.fields["bank_account"].required = True
        self.fields["tel"].required = True

    class Meta:
        model = UserBank
        fields = [ 'bank_name', 'bank_account',
                  'tel',]

    def clean_vcode(self):
        data = self.cleaned_data['vcode']
        if not data:
            raise forms.ValidationError(u'这个字段是必填项。')
        return data

    def clean_bank_account(self):
        data = self.cleaned_data['bank_account']
        if not is_valid_bank_card_num(data):
            raise forms.ValidationError(u'卡号不合法。')
        return data

    def clean_bank_name(self):
        data = self.cleaned_data['bank_name']
        if not is_valid_bank(data):
            raise forms.ValidationError(u'不支持该银行。')
        return data

    def clean_tel(self):
        data = self.cleaned_data['tel']
        if not is_valid_mobile(data):
            raise forms.ValidationError(u'手机号不合法。')
        return data

    def save(self, *args, **kwargs):

        super(self.__class__, self).save(*args,**kwargs) # Call the "real" save() method.

demo/apps/customer/user_info/forms.py
# -*- coding: utf-8 -*-

from django import forms
from demo.apps.customer.assets.utils import is_valid_mobile, is_valid_bank_card_num, is_valid_bank


class UserInfoForm(forms.Form):

    nickname = forms.CharField(max_length=100)
    sex = forms.RadioSelect()
    birthday = forms.DateField()
    interest = forms.Textarea()
    real_name = forms.CharField()
    mobile_phone = forms.CharField()
    email = forms.EmailField(label=u'邮箱')

    address = forms.CharField()

    region = forms.IntegerField()

demo/templates/base_footbar.html
{% block footer %}
<!--footer start-->
<div class="footer">
    <div class="container center">
        <div>
            <ul class="footer-menu fix">
                <li><a href="{% url 'helper:helper_index' %}">帮助中心</a><span>|</span></li>
                <li><a href="{% url 'helper:helper_index' %}">新手指导</a><span>|</span></li>
                <li><a href="#">商家入驻</a><span>|</span></li>
                <li><a href="{% url 'helper:helper_index' %}">常见问题</a><span>|</span></li>
                <li><a href="#">意见建议</a><span>|</span></li>
                <li><a href="#">问题反馈</a><span>|</span></li>
                <li><a href="#">关于我们</a><span>|</span></li>
                <li><a href="#">加入我们</a><span>|</span></li>
            </ul>
        </div>
             <p>
                有意与本网合作者，有关合作事宜请与《宁夏蓝图商品交易市场有限公司》联系。未经《宁夏蓝图商品交易市场有限公司》书面授权，请勿转载或建立镜像，否则即为侵权。
            </p>
            <p>地址：宁夏银川市西夏区兴泾镇黄花村西夏国际公铁物流城商务服务中心四楼东侧 邮编：750000 客服电话：4008-777-610</p>
            <p>宁ICP备14001885号-1 Copyright©  2007-2015 蓝图商品 ltbot.com 版权所有 复制必究</p>
        <!--<div class="footer-web">-->
            <!--<span class="di-1"></span>-->
            <!--<span class="di-2"></span>-->
            <!--<span class="di-3"></span>-->
            <!--<span class="di-4"></span>-->
            <!--<span class="di-5"></span>-->
        <!--</div>-->
    </div>
</div>
{% endblock %}

demo/templates/base_stars.html
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% load currency_filters %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="renderer" content="webkit">
    <link rel="shortcut icon" href="{% static "images/web_logo.ico" %}" />
    <link rel="stylesheet" href="{% static "css/public.css" %}" type="text/css">
    {% block public_css %}
    {% endblock %}
    {% block custom_css %}
        <link rel="stylesheet" href="{% static "css/product.css" %}" type="text/css">
    {% endblock %}
    {% block jquery %}
        <script type="text/javascript" src="{% static "js/jquery-1.11.1.min.js" %}"></script>
    {% endblock %}
    {% block custom_js %}
    {% endblock %}

    
    <title>{% block title %}蓝图百货{% endblock %}</title>
</head>
<body>
    {% block top %}
    <!--顶部 start-->
    <div class="top">
        {% block topmenu %}
        <!--顶层状态、登录条-->
        <div class="login">
            <div class="container fix">
                <div class="l login-left">
                    {% if user.is_authenticated %}
                    <span>{% trans "Welcome" %}&nbsp; <em>{{ user.username }}</em></span>
                    &nbsp;
                    <a href="{% url "accounts:logout" %}">注销</a>
                    {% else %}
                    <a href="{% url "accounts:login" %}">登录</a>
                    <a href="{% url "accounts:register" %}">注册</a>
                    {% endif %}
                </div>
                {% if user.is_authenticated %}
                <ul class="r login-right">
                    <li class="first-menu">
                        <a href="{% url 'customer:order_manage' %}">我的账户<span class="jt"></span></a>
                    </li>
                    <li class = "first-menu">
                        <a href="{% url 'helper:helper_index' %}">帮助中心<span class="jt"></span></a>
                        <ul>
                            <li><a href="{% url 'helper:helper_index' %}">新手指导</a></li>
                            <li><a href="{% url 'helper:helper_index' %}">常见问题</a></li>
                        </ul>
                    </li>
                </ul>
                {% else %}
                <ul class="r login-right">
                    <li>
                        <a href="{% url 'accounts:login' %}">我的账户</a>
                    </li>
                    <li><a href="{% url 'accounts:login' %}">充值</a></li>
                    <li>
                        <a href="{% url 'helper:helper_index' %}">帮助中心<span class="jt"></span></a>
                        <ul>
                            <li><a href="{% url 'helper:helper_index' %}">新手指导</a></li>
                            <li><a href="{% url 'helper:helper_index' %}">常见问题</a></li>
                        </ul>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
        {% endblock %}
        {% block logo %}
        <!--logo、搜索、购物车-->
        <div class="logo container fix">
            <div class="logo-img1 l">
                <a href ="{% url 'promotions:home' %}"><img src="{% static "images/logo-1.png" %}"/></a>
            </div>
            <div class="search-box l">
                <form method="get" action="{% url 'catalogue:allproducts' %}" class="form-horizontal">
                {% csrf_token %} 
                <div class="input-t">
                {% if kwargs.search_q %}
                    <input type="text" name="q" value="{{kwargs.search_q}}" onfocus="OnfocusFun(this,'输入商品名、货号、商品关键字')" onblur="OnBlurFun(this,'输入商品名、货号、商品关键字')" style='color:#999;'/>
                {% else %}
                    <input type="text" name="q" value="输入商品名、货号、商品关键字" onfocus="OnfocusFun(this,'输入商品名、货号、商品关键字')" onblur="OnBlurFun(this,'输入商品名、货号、商品关键字')" style='color:#999;'/>
                {% endif %}  
                    <span class="search-img"></span>
                </div>
                <div class="input-s">
                    <input type="submit" value="搜索"/>
                </div>
                </form>
                <ul class="keywords l">
                     <li><a>红酒</a><span>|</span></li>
                    <li><a class="color-red">白酒</a><span class="color-h">|</span></li>
                    <li><a>啤酒</a><span class="color-h">|</span></li>
                    <li><a>洋酒</a><span class="color-h" style="display: none;">|</span></li>
                </ul>
            </div>
        </div>
        {% endblock %}
    </div>
    {% endblock %}
    <!--顶部 end-->
    
    <!--顶部搜索 -->
{% block searchfix %}
    <div class="searchFix" style="display: none;">
        <div class="container fix">
            <div class="fix-logo l"><img src="{%static 'images/logo3交易大厅.png' %}" /></div>
            <div class="search-box search-box2 l">
            <form method="get" action="{% url 'catalogue:allproducts' %}" >
            <div class="input-t">
                <input type="text" name="q" value="输入商品名、货号、商品关键字" onfocus="OnfocusFun(this,'输入商品名、货号、商品关键字')" onblur="OnBlurFun(this,'输入商品名、货号、商品关键字')" style='color:#999;'/>
                <span class="search-img"></span>
            </div>
            <div class="input-s">
                <input type="submit" value="搜索" />
            </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

    {% block content %}
    {% endblock %}
    
    {% block to-top %}
	 <div class="fix-to-top">
        <div class="to-top" style="display: none;">
            <a><img src="{% static 'images/top.png'%}"/></a>
        </div>
        <div class="kefu" style="display: none;">
            <a><img src="{%static 'images/kefu.png'%}"/></a>
        </div>
    </div>
    {% endblock %}
  

    {% include "base_footbar.html" %}

    {% block footer_script %}
        <script type="text/javascript">
            //得到焦点触发事件
            function OnfocusFun(element,elementvalue)
            {
                if(element.value==elementvalue)
                {
                    element.value="";
                    element.style.color="#343434";
                }
            }
            //离开输入框触发事件
            function OnBlurFun(element,elementvalue)
            {
                if(element.value=="" || element.value.replace(/\s/g,"")=="")
                {
                    element.value=elementvalue;
                    element.style.color="#999";
                }
            }

            $(function(){
                $(".shop-list>ul>li").click(function(){
                $(".shop-list>ul>li>ul").hide();
                $("ul",this).slideDown(500);
                });
                
                //固定搜索栏
                $(window).scroll(function(){
                    var curHeight=$(document).scrollTop();
                    if(curHeight>=400){
                        $(".searchFix").slideDown();
                        $(".to-top").show();
                    }else{
                        $(".searchFix").slideUp();
                        $(".to-top").hide();
                    }
                });
                $(".to-top").click(function(){
                    $(window).scrollTop(0);
                });

        function menuFix() {
        var sfEls = document.getElementById("lid");
        for (var i=0; i<sfEls.length; i++) {
        sfEls[i].onmouseover=function() {
        this.className+=(this.className.length>0? " ": "") + "sfhover";
        }
        sfEls[i].onMouseDown=function() {
        this.className+=(this.className.length>0? " ": "") + "sfhover";
        }
        sfEls[i].onMouseUp=function() {
        this.className+=(this.className.length>0? " ": "") + "sfhover";
        }
        sfEls[i].onmouseout=function() {
        this.className=this.className.replace(new RegExp("( ?|^)sfhover\\b"),"");
        }
        }
        }
       
        
            window.onload=menuFix;
            window.onload = function(){
                $(".keywords").find("li").eq(-1).children("span").css("display","none");
                $(".footer-menu").find("li").eq(-1).children("span").css("display","none");
            };
            

            
            
        </script>


    {% endblock %}
</body>
</html>