demo/apps/accounts/urls.py
# encoding: utf-8


from django.conf.urls import patterns, url, include

urlpatterns = patterns('demo.apps.accounts.views',
    url(r'^check-mobile-phone/$', 'check_mobile_phone', name='check_mobile_phone'),
    url(r'^check-register-mobile-phone/$', 'check_register_mobile_phone', name='check_register_mobile_phone'),
    url(r'^check-username/$', 'check_username', name='check_username'),
    url(r'^check-introducer/$', 'check_introducer', name='check_introducer'),
    url(r'^register/$', 'register', name='register'),
    url(r'^send-captcha/$', 'send_captcha', name='send_captcha'),
    url(r'^user-agreement/$', 'user_agreement', name='user_agreement'),
    url(r'^set-identity/(?P<userprofile_id>\d+)/$', 'set_identity', name='set_identity'),
    url(r'^register-finish/(?P<user_id>\d+)/$', 'register_finish', name='register_finish'),
    url(r'^login/$', 'user_login', name='login'),
    url(r'^logout/$', 'user_logout', name='logout'),
    # url(r'^reset-password/$', 'reset_password', name='reset_password'),
    # url(r'^logout/$', 'user_logout', name='logout'),
    url(r'^forgetpw/$','forgetpw',name='forgetpw'),
    url(r'^resetpw/$','resetpw',name='resetpw'),
    url(r'^resetpw-finish/$','resetpw_finish',name = 'resetpw_finish'),
)

demo/apps/api/urls.py
# coding=utf-8
from django.conf.urls import patterns, url, include
from rest_framework.authentication import BasicAuthentication
from rest_framework_jwt.authentication import JSONWebTokenAuthentication

from demo.apps.api.views import (APIRegisterView, APIGetsmscodeView,
    APITestTokenView, APILoginView, APIGetimgverifycodeView, APIFindpwdView,
    APIResetpwdView, APICheckusernameView, APIUpdateusernameView, 
    APIGetOrdersView, APIGetOrderDetailView, APICancelOrderView)

urlpatterns = patterns('',
    url(r'^auth/', 'rest_framework_jwt.views.obtain_jwt_token', name='api_auth'),
)

urlpatterns += patterns('demo.apps.api.views',
    url(r'^test/$', APITestTokenView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='test'),
    # about account
    url(r'^getsmscode/$', APIGetsmscodeView.as_view(authentication_classes=[BasicAuthentication]), name='api_getsmscode'),
    url(r'^getimgverifycode/$', APIGetimgverifycodeView.as_view(authentication_classes=[BasicAuthentication]), name='api_getimgverifycode'),
    url(r'^findpwd/$', APIFindpwdView.as_view(authentication_classes=[BasicAuthentication]), name='api_findpwd'),
    url(r'^resetpwd/$', APIResetpwdView.as_view(authentication_classes=[BasicAuthentication]), name='api_resetpwd'),
    url(r'^checkusername/$', APICheckusernameView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='api_checkusername'),
    url(r'^updateusername/$', APIUpdateusernameView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='api_updateusername'),
    url(r'^register/$', APIRegisterView.as_view(authentication_classes=[BasicAuthentication]), name='api_register'),
    url(r'^login/$', APILoginView.as_view(authentication_classes=[BasicAuthentication]), name='api_login'),

    url(r'^getorderdetail/(?P<order_id>\d+)/$', APIGetOrderDetailView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='api_getorderdetail'),
    url(r'^cancelorder/(?P<order_id>\d+)/$', APICancelOrderView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='api_cancelorder'),
    url(r'^getorders/$', APIGetOrdersView.as_view(authentication_classes=[JSONWebTokenAuthentication]), name='api_getorders'),
)

demo/apps/helper/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required



urlpatterns = patterns('demo.apps.helper.views',
    url(r'^$', 'helper_index', name='helper_index'),
)

demo/urls.py
# -*- coding: utf-8 -*-s

"""demo URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url, patterns
from django.conf import settings
from django.contrib import admin
from oscar.app import application

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('demo.apps.accounts.urls', namespace='accounts')),
    url(r'^helper/', include('demo.apps.helper.urls', namespace='helper')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'platform/', include('demo.apps.platform.urls', namespace='platform')),
    url(r'^api/', include('demo.apps.api.urls', namespace='api')),
    url(r'', include(application.urls)),
]

# 部署时下面两个注释要解开
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 部署时下面4行要注释 （这个是本地测试404页面用的）
urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT },name='media'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.STATICFILES_DIRS[0] },name='static'),
)

demo/apps/accounts/models.py
# -*- coding: utf-8 -*-s

import random

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
from demo.apps.address.models import District

from demo.apps.accounts.role_validate import is_specific_role

ROLE_CHOICE = (('member', u'会员'), ('ISP', u'厂商'), ('dashboard_admin', u'后台管理员'),
        ('warehouse_staff', u'仓库人员'), ('member_unit', u'会员单位'),
        ('trader', u'交易员'))


class UserProfile(models.Model):
    VERIFIED_STATUS_CHOICE=((0, u'未认证'),(1, u'认证中'),(2, u'认证成功'),(3, u'认证失败'))
    SEX_CHOICE=((1, u'男'),(2, u'女'), (3, u'保密'))
    CERT_TYPE_CHOICE=((0, u'身份证'),(1, u'组织机构代码'))
    user = models.OneToOneField(User, verbose_name=u'用户')
    uid = models.IntegerField(blank=True, null=True, verbose_name='uid')
    username_checked = models.BooleanField(default=False, verbose_name='是否修改过用户名')
    funds_password = models.CharField(max_length=128, blank=True, null=True,
                                      verbose_name=u'资金密码')
    mobile_phone = models.CharField(max_length=15, unique=True,
                                    verbose_name=u'手机号码')
    avatar = models.ImageField(upload_to=settings.AVATAR_ROOT, blank=True, null=True,
                               verbose_name=u'头像')
    real_name = models.CharField(max_length=127, default='', blank=True, null=True,
                                 verbose_name=u'真实姓名')
    cert_type = models.SmallIntegerField(choices=CERT_TYPE_CHOICE, default=0, blank=True,null=True,
                                         verbose_name=u'证件类型')
    identification_card_number = models.CharField(max_length=32, blank=True,
                                                  null=True, verbose_name=u'身份证号')
    identification_card_image_front = models.ImageField(upload_to='identification_card',
                                                        blank=True, null=True, verbose_name=u'身份证正面图')
    identification_card_image_back = models.ImageField(upload_to='identification_card',
                                                       blank=True, null=True, verbose_name=u'身份证背面图')
    role = models.CharField(max_length=100, choices=ROLE_CHOICE, verbose_name=u'角色',
                            default='member')
    nickname = models.CharField(max_length=127, default='', blank=True, null=True,
                                 verbose_name=u'昵称')
    sex = models.PositiveSmallIntegerField(default=3, choices=SEX_CHOICE, verbose_name=u'性别')
    birthday = models.DateField(blank=True, null=True)
    interest = models.CharField(default='', blank=True, null=True, max_length=200, verbose_name=u'兴趣')
    region = models.ForeignKey(District, verbose_name=u'地区', null=True, blank=True)
    address = models.CharField(default='', blank=True, null=True, max_length=200, verbose_name=u'详细地址')

    # audit_status = models.BooleanField(default=False, verbose_name=u'审核通过状态')

    audit_status = models.PositiveSmallIntegerField(default=0, choices=VERIFIED_STATUS_CHOICE, verbose_name=u'认证状态')

    pay_pwd = models.CharField(blank=True, null=True, max_length=128, verbose_name=u'资金密码')
    pickup_pwd = models.CharField(blank=True, null=True, max_length=128, verbose_name=u'提货密码')
    desc = models.CharField(default='', blank=True, null=True, max_length=1000, verbose_name=u'备注')
    introducer = models.CharField(max_length=64, blank=True, null=True, verbose_name=u'推荐人')
    register_ip = models.CharField(max_length=64, blank=True, null=True, verbose_name=u'注册IP')
    created_date = models.DateField(auto_now_add=True, db_index=True, verbose_name=u'创建日期')
    created_time = models.TimeField(auto_now_add=True, verbose_name=u'创建时间')
    modified_date = models.DateField(auto_now=True, verbose_name=u'修改日期')
    modified_time = models.TimeField(auto_now=True, verbose_name=u'修改时间')

    class Meta:
        verbose_name = verbose_name_plural = u'用户额外信息'

    def get_avatar(self):
        if self.avatar:
            return self.avatar.url
        else:
            return settings.DEFAULT_AVATAR

    def __unicode__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if self.role != 'member':
            self.user.is_staff = True
            self.user.save()
        if not self.uid:
            self.uid = self.user.id + 10000000
        super(UserProfile, self).save(*args, **kwargs)

    def is_dashboard_admin(self):
        return is_specific_role(self.user, 'dashboard_admin')

    def is_ISP(self):
        return is_specific_role(self.user, 'ISP')

    def is_warehouse_staff(self):
        return is_specific_role(self.user, 'warehouse_staff')

    def is_member_unit(self):
        return is_specific_role(self.user, 'member_unit')

    def is_trader(self):
        return is_specific_role(self.user, 'trader')


def save_additional_info(sender, **kwargs):
    current_user = kwargs['instance']
    try:
        current_userprofile = current_user.userprofile
    except UserProfile.DoesNotExist:
        exist_mobile_phone = True
        while exist_mobile_phone:
            new_mobile_phone = random.randint(10000000000, 99999999999)
            try:
                current_userprofile = UserProfile.objects.get(mobile_phone=new_mobile_phone)
            except UserProfile.DoesNotExist:
                exist_mobile_phone = False
        UserProfile.objects.create(user=current_user, mobile_phone=new_mobile_phone)


post_save.connect(receiver=save_additional_info, sender=User, weak=False)


class Captcha(models.Model):
    recipient = models.CharField(max_length=32, unique=True, verbose_name=u'手机号码')
    captcha = models.CharField(max_length=15, verbose_name=u'验证码')
    deadline_time = models.DateTimeField(blank=True, null=True, verbose_name=u'过期时间')

    class Meta:
        verbose_name = verbose_name_plural = u'验证码'

    def __unicode__(self):
        return self.recipient

demo/apps/ad/models.py
from abstract_models import AbstractRollingAd
from oscar.core.loading import is_model_registered

__all__ = []

__APP_LABEL__ = 'ad'
if not is_model_registered(__APP_LABEL__, 'RollingAd'):
    class RollingAd(AbstractRollingAd):
        pass
    __all__.append('RollingAd')

demo/apps/basket/models.py
from oscar.apps.basket.models import *  # noqa

demo/apps/checkout/models.py
from oscar.apps.checkout.models import *  # noqa

demo/apps/customer/models.py
from oscar.apps.customer.models import *  # noqa

demo/apps/customer/stock/models.py
# -*- coding: utf-8 -*-s

from django.db import models

from django.contrib.auth.models import User
from oscar.core.loading import get_model



Product = get_model('catalogue', 'Product')


PICKUP_TYPE = (
    (1, '购买'),
    (2, '进货'),
    (3, '全部'),
)


class PickupProvisionalRecord(models.Model):
    user = models.ForeignKey(User, verbose_name=u'用户')
    product = models.ForeignKey(Product, verbose_name=u'商品')
    quantity = models.IntegerField(default=1, verbose_name=u'提货数量')
    max_quantity = models.IntegerField(verbose_name=u'货物余量')
    available = models.BooleanField(default=False, verbose_name=u'是否可用')
    pickup_type = models.IntegerField(default=1,
                                      choices=PICKUP_TYPE, verbose_name=u'提货类型')


    class Meta:
        verbose_name = verbose_name_plural = u'提货临时记录'
        unique_together = ('user', 'product')

    def __unicode__(self):
        return self.user.username

demo/apps/promotions/models.py
from oscar.apps.promotions.models import *  # noqa

demo/apps/customer/assets/forms.py
# -*- coding: utf-8 -*-

from django import forms
from demo.apps.commission.models import UserBank

from demo.apps.customer.assets.utils import is_valid_mobile, is_valid_bank_card_num, is_valid_bank


class BankCardForm(forms.ModelForm):

    def __init__(self, user,*args, **kwargs):
        self.user = user
        super(self.__class__, self).__init__(*args, **kwargs)
        # self.fields["user_name"].required = True
        # self.fields["id_card"].required = True
        # self.user = user
        self.fields["bank_name"].required = True
        self.fields["bank_account"].required = True
        self.fields["tel"].required = True

    class Meta:
        model = UserBank
        fields = [ 'bank_name', 'bank_account',
                  'tel',]

    def clean_vcode(self):
        data = self.cleaned_data['vcode']
        if not data:
            raise forms.ValidationError(u'这个字段是必填项。')
        return data

    def clean_bank_account(self):
        data = self.cleaned_data['bank_account']
        if not is_valid_bank_card_num(data):
            raise forms.ValidationError(u'卡号不合法。')
        return data

    def clean_bank_name(self):
        data = self.cleaned_data['bank_name']
        if not is_valid_bank(data):
            raise forms.ValidationError(u'不支持该银行。')
        return data

    def clean_tel(self):
        data = self.cleaned_data['tel']
        if not is_valid_mobile(data):
            raise forms.ValidationError(u'手机号不合法。')
        return data

    def save(self, *args, **kwargs):

        super(self.__class__, self).save(*args,**kwargs) # Call the "real" save() method.

demo/apps/customer/receiving_address/forms.py
#!/usr/bin/env python
# encoding: utf-8


from django import forms

from stars.apps.address.models import ReceivingAddress
from stars.apps.accounts.forms import (local_mobile_phone_validator,
                                       local_phone_validator)


class ReceivingAddressForm(forms.ModelForm):
    class Meta:
        model = ReceivingAddress
        exclude = ['user', ]
        widgets = {
            'province': forms.Select(attrs={'class':'input-group-select l'}),
            'city': forms.Select(attrs={'class':'input-group-select l'}),
            'district': forms.Select(attrs={'class':'input-group-select l'}),
            'address': forms.TextInput(attrs={'class':'input-long'}),
            'mobile_phone': forms.TextInput(attrs={'class':'input-short'}),
            'telephone': forms.TextInput(attrs={'class':'input-short'}),
            'email': forms.TextInput(attrs={'class':'input-short'}),
        }

    def clean_mobile_phone(self):
        data = self.cleaned_data['mobile_phone']

        if not local_mobile_phone_validator(data):
            raise forms.ValidationError(u'手机号码不合法。')
        return data

    def clean_telephone(self):
        data = self.cleaned_data['telephone']

        if not local_phone_validator(data):
            raise forms.ValidationError(u'电话号码不合法。')
        return data

demo/apps/customer/safety/forms.py
# -*- coding: utf-8 -*-

from django import forms

from demo.apps.accounts.models import UserProfile
from demo.apps.customer.safety.utils import is_valid_id_card_num


class RealNameAuthForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        self.fields["real_name"].required = True
        self.fields["identification_card_number"].required = True
        self.fields["identification_card_image_front"].required = True
        self.fields["identification_card_image_back"].required = True

    class Meta:
        model = UserProfile
        fields = ['real_name', 'identification_card_number',
                  'identification_card_image_front', 'identification_card_image_back']

    def clean_identification_card_number(self):
        data = self.cleaned_data['identification_card_number']
        if not is_valid_id_card_num(data):
            raise forms.ValidationError(u'身份证号码不合法。')
        return data

    def save(self, *args, **kwargs):
        # self.identification_card_image_front

        super(self.__class__, self).save(*args,**kwargs) # Call the "real" save() method.

demo/apps/customer/user_info/forms.py
# -*- coding: utf-8 -*-

from django import forms
from demo.apps.customer.assets.utils import is_valid_mobile, is_valid_bank_card_num, is_valid_bank


class UserInfoForm(forms.Form):

    nickname = forms.CharField(max_length=100)
    sex = forms.RadioSelect()
    birthday = forms.DateField()
    interest = forms.Textarea()
    real_name = forms.CharField()
    mobile_phone = forms.CharField()
    email = forms.EmailField(label=u'邮箱')

    address = forms.CharField()

    region = forms.IntegerField()

demo/templates/accounts/forgetpw.html
{% extends 'base_stars.html' %}
{% load staticfiles %}

{% block public_css %}
    <link rel="stylesheet" href="{% static "css/register.css" %}" type="text/css">
{% endblock %}
{% block jquery %}
<script type="text/javascript" src="{% static "js/jquery-1.11.1.min.js" %}"></script>
{% endblock %}

{% block title %}蓝图百货—忘记密码{% endblock %}

{% block logo %}
    <div class="register-topbar">
        <div class="container fix">
            <div class="register-topbar-left l">
            <a href="/">
                <img src="{% static "images/logo1.png" %}" />
            </a>
            </div>
            <div class="register-topbar-right r">
                忘记密码
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="register-body">
	<div class="container">
		<div class="register-body-top fix">
			<div class="box l center">
				<span class="line line-yellow"></span> <span class="txt">验证身份</span>
				<img src="{% static "images/register-oval1h.png" %}" class="img" />
			</div>
			<div class="box l center">
				<span class="line"></span> <span class="txt">设置新密码</span> <img
					src="{% static "images/register-oval2.png" %}" class="img" />
			</div>
			<div class="box l center">
				<span class="line"></span> <span class="txt">完成修改</span> <img
					src="{% static "images/register-oval3.png" %}" class="img" />
			</div>
		</div>
<form class="register-form register-form1" method="post" action="">
                {% csrf_token %}
                <div class="input-group fix">
                    <div class="input-group-left right l">
                        <span class="color-red">*</span>
                        输入注册的手机号：
                    </div>
                    <div class="input-group-right l">
                        {{ form.mobile_phone }}

                        {% if form.mobile_phone.errors %}
                            <div class="img">
                                <img src="{% static "images/register-error.png" %}"/>
                                <span class="color-red">{{ form.mobile_phone.errors }}</span>
                            </div>
                        {% else %}
                            {% if post %}
                                <div class="img">
                                    <img src="{% static "images/register-right.png" %}"/>
                                </div>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div class="input-group fix">
                    <div class="input-group-left right l">
                        <span class="color-red">*</span>
                        验证码：
                    </div>
                    <div class="input-group-right l">
                        {{ form.captcha }}
                        <div class="get-code" id="get-code">
                         <span class="send" id="J_getCode">获取验证码</span>
                         <div class="send send-cover" id="J_getCode_Cover">获取验证码</div>                       
                        </div>
                        {% if form.captcha.errors %}
                            <div class="img">
                                <img src="{% static "images/register-error.png" %}"/>
                                <span class="color-red">{{ form.captcha.errors }}</span>
                            </div>
                        {% else %}
                            {% if post %}
                                <div class="img">
                                    <img src="{% static "images/register-right.png" %}"/>
                                </div>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div class="register-btn">
                    <input type="submit" value="下一步"/>
                </div>
   </form>

	</div>
</div>
{% endblock %}

{% block footer_script %}
<script type="text/javascript">
window.onload = function(){
    $(".footer-menu").find("li").eq(-1).children("span").css("display","none");
};

//得到焦点触发事件
function OnfocusFun(element,elementvalue)
{
    if(element.value==elementvalue)
    {
        element.value="";
        element.style.color="#343434";
    }
}
//离开输入框触发事件
function OnBlurFun(element,elementvalue)
{
    if(element.value=="" || element.value.replace(/\s/g,"")=="")
    {
        element.value=elementvalue;
        element.style.color="#999";
    }
}
//得到焦点触发事件
function OnfocusFun1(element,elementvalue)
{
    if(element.value==elementvalue)
    {
        element.value="";
        element.type="password";
        element.style.color="#343434";
    }
}
//离开输入框触发事件
function OnBlurFun1(element,elementvalue)
{
    if(element.value=="" || element.value.replace(/\s/g,"")=="")
    {
        element.value=elementvalue;
        element.type="text";
        element.style.color="#999";
    }
}


//验证码倒计时60秒
var wait = 60;
function time(t){
	if(wait<=0){
		t.css("display","block");
		$("#J_getCode").css("background-color","#0a8fc7");
		t.html("重新获取");
		$("#J_getCode").html("重新获取");
		wait = 60 ;
	}
	else{
		t.css("display","none");
		$("#J_getCode").css("background-color","#bfbfbf");
		$("#J_getCode").html("等待 ("+wait+")");
		wait--;
		setTimeout(function(){time(t)},1000);
	}
}

// 加载 事件
$(function(){
/* 	$("#id_mobile_phone").blur(function(){
        var mobile_phone = $(this).val();
        $.ajax({
            dataType: "json",
            url: "{% url 'accounts:check_register_mobile_phone' %}",
            data: {'mobile_phone': mobile_phone},
            success: function (result) {
                if ($("#id_mobile_phone").next()) {
                    $("#id_mobile_phone").next().remove();
                }
                if (result.error) {
                    $("#id_mobile_phone").after('<div class="img"><img src="{% static "images/register-error.png" %}"/><span class="color-red">' + result.error + '</span></div>');
                }
            },
        });
    });
	 */
	
	$("#id_mobile_phone").change(function(){
        var mobile_phone = $(this).val();
        $.ajax({
            dataType: "json",
            url: "{% url 'accounts:check_register_mobile_phone' %}",
            data: {'mobile_phone': mobile_phone},
            success: function (result) {
                if ($("#id_mobile_phone").next()) {
                    $("#id_mobile_phone").next().remove();
                }
                if (result.error) {
                    $("#id_mobile_phone").after('<div class="img" id="null_pone">&nbsp;<img src="{% static "images/register-error.png" %}"/><span class="color-red">' + result.error + '</span></div>');
                }
            },
        });
    });
	
	$("#J_getCode_Cover").click(function(){
        var phonenum = /^[0-9]{11}$/;
        var that = $(this);
        var phone = $("#id_mobile_phone").val();
        var params = {};
        //如果表单里有手机号码输入框，但用户未填写手机号码，则弹窗并中止
        if (!phone){
                $("#null_pone").remove();
                var text = '<div class="img" id="null_pone">\
                    &nbsp;<img src="{% static "images/register-error.png" %}"/>\
                    <span class="color-red">手机号不能为空！</span></div>';
                $("#get-code").after(text);
                return;
            };
            alert(4);
        if (!phonenum.test(phone)) {
        	 $("#null_pone").remove();
             var text = '<div class="img" id="null_pone">\
                 &nbsp;<img src="{% static "images/register-error.png" %}"/>\
                 <span class="color-red">手机号码不合法.</span></div>';
             $("#get-code").after(text);
            return;
        }
         if (phone) {
                params.phone = phone;
         }
         alert(5);
         $.ajax({
             dataType: "json",
             url: "{% url "accounts:send_captcha" %}",
             data: params,
             success: function (json) {
                 if (json.result) {
                     alert('短信发送成功');
                 }
                 else {
                     alert('短信发送失败');
                 }
             },
             error: function (error) {
                 alert('短信发送失败');
             }
         });
         
	
	    time($(this));
    });

	
})



</script>
{% endblock %}

demo/templates/accounts/resetpw_finish.html
{% extends 'base_stars.html' %}
{% load staticfiles %}

{% block public_css %}
    <link rel="stylesheet" href="{% static "css/register.css" %}" type="text/css">
{% endblock %}
{% block jquery %}
<script type="text/javascript" src="{% static "js/jquery-1.11.1.min.js" %}"></script>
{% endblock %}

{% block title %}蓝图百货—忘记密码{% endblock %}

{% block logo %}
    <div class="register-topbar">
        <div class="container fix">
            <div class="register-topbar-left l">
            <a href="/">
                <img src="{% static "images/logo1.png" %}" />
            </a>
            </div>
            <div class="register-topbar-right r">
                忘记密码
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
   <div class="register-body register-body1">
        <div class="container">
            <div class="register-body-top fix">
                <div class="box l center">
                    <span class="line"></span>
                    <span class="txt">验证账户</span>
                    <img src="{% static "images/register-oval1.png" %}" class="img"/>
                </div>
                <div class="box l center">
                    <span class="line"></span>
                    <span class="txt">设置新密码</span>
                    <img src="{% static "images/register-oval2.png" %}" class="img"/>
                </div>
                <div class="box l center">
                    <span class="line line-yellow"></span>
                    <span class="txt">完成修改</span>
                    <img src="{% static "images/register-oval3h.png" %}" class="img"/>
                </div>
            </div>
            <div class="register-body-content">
                <div class="finish-txt2 center">
                    <img src="{% static 'images/sub-success.png' %}"/>
                    <span>登录密码修改成功!</span>
                    <div class="re-login">
                        {{ user.username }},您的密码已经修改成功！现在去&nbsp;&nbsp;<a href="{% url 'accounts:login' %}" style = "color:#0088cc">登录</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}